server:
  port: 8085

spring:
  application:
    name: ms-spring-webflux-sql
  r2dbc:
    url: r2dbc:postgresql://ep-holy-cloud-adfy3yps-pooler.c-2.us-east-1.aws.neon.tech/luis_rivas_32?sslmode=verify-full
    username: neondb_owner
    password: npg_QdXrn6pgmxV0
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
  logging:
    level:
      org.springframework.r2dbc: DEBUG

springdoc:
  api-docs:
    enable: true
    path: /api-docs
  swagger-ui:
    enable: true
    path: /swagger-ui.html